name: build-action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 13
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Check out linux-tkg repository
        uses: actions/checkout@v3
        with:
          repository: Frogging-Family/linux-tkg
          path: linux-tkg
#      - name: Check out CachyOS kernel-patches repository
#        uses: actions/checkout@v3
#        with:
#          repository: CachyOS/kernel-patches
#          path: kernel-patches
#cp $GITHUB_WORKSPACE/kernel-patches/6.1/0001-bbr2.patch $GITHUB_WORKSPACE/linux-tkg/linux61-tkg-userpatches/
      - name: Check out Xanmod linux-patches repository
        uses: actions/checkout@v3
        with:
          repository:  xanmod/linux-patches 
          path: linux-patches
      - name: Prepare for build
        run: |
           cd $GITHUB_WORKSPACE/linux-tkg/linux-tkg-config/6.1
           /bin/bash $GITHUB_WORKSPACE/update-config.sh
           mkdir $GITHUB_WORKSPACE/linux-tkg/linux61-tkg-userpatches
           cp $GITHUB_WORKSPACE/linux-patches/linux-6.1.y-xanmod/net/bbr2/* $GITHUB_WORKSPACE/linux-tkg/linux61-tkg-userpatches/
           cd $GITHUB_WORKSPACE/linux-tkg/linux61-tkg-userpatches
           /bin/bash $GITHUB_WORKSPACE/rename-patch.sh
           /usr/bin/sed -i 's/"bbr"/"bbr2"/g' $GITHUB_WORKSPACE/linux-tkg/linux-tkg-config/prepare
           /usr/bin/sed -i 's/"FUNCTION_GRAPH_TRACER"/"FUNCTION_GRAPH_TRACER" "STACK_TRACER"/g' $GITHUB_WORKSPACE/linux-tkg/linux-tkg-config/prepare
           cp $GITHUB_WORKSPACE/customization.cfg.bore  $GITHUB_WORKSPACE/linux-tkg/customization.cfg
      - name: Build kernel
        run: |
           docker run -e USERID=$(id -u $(whoami)) -e GITHUB_TOKEN=${{ secrets.pat }} -v $GITHUB_WORKSPACE:/workspace archlinux:latest /bin/bash /workspace/build.sh
           cp $GITHUB_WORKSPACE/linux-tkg/*.pkg.tar.zst /tmp
      - uses: actions/upload-artifact@v3
        with:
          name: linux-tkg-bore-llvm
          path: /tmp/*.pkg.tar.zst
